Repository popi-official/popi-user-client, pull requests merged in 2025-06, with the labels that each got.

#37 fix: 장바구니 상품 재고 수량 제한 로직 추가
  app/(common)/search/index.tsx
  app/(tabs)/cart/index.tsx
  src/components/searchScreen/searchResultPopUp/SearchResultPopUpItem.tsx
  src/hooks/api/usePopUpDetailApi.ts
  src/store/useCartStore.ts
Labels: ✨ feature

#38 feat: 마이페이지 결제내역 구현
  app/(common)/qrCamera/index.tsx
  app/(tabs)/_layout.tsx
  app/(tabs)/my/Style.style.ts
  app/(tabs)/my/index.tsx
  app/+html.tsx
  app/_layout.tsx
  app/index.tsx
  src/apis/payment/PaymentApi.ts
  src/hooks/api/usePaymantApi.ts
  src/mocks/MyPageChecks.ts
  src/store/useAuthStore.ts
  src/types/MyPageScreen.ts
  src/types/api/ApiResponseType.ts
Labels: ✨ feature

#45 test: 테스트 케이스 구조 분리
  __test__/Login.test.tsx
  __test__/Payment.test.tsx
  __test__/Reservation.test.tsx
  __test__/Search.test.tsx
  __test__/Signup.test.tsx
Labels: ✅ test

#48 fix: Mock 데이터 제거 & 사용하지 않는 함수 제거
  React_Native_이미지_성능_최적화_가이드.html
  React_Native_이미지_성능_최적화_가이드.md
  android/app/src/main/AndroidManifest.xml
  android/gradle.properties
  app/(tabs)/home/index.tsx
  src/components/BottomSheetExample.tsx
  src/components/Example.tsx
  src/components/TestScreen.style.ts
  src/components/entireItems/searchBar/SearchBar.style.ts
  src/components/entireItems/searchBar/SearchBar.tsx
  src/components/header/right/homeHeaderRight/HomeHeaderRight.style.ts
  src/constants/OnBoarding.ts
  src/mocks/HomeMocks.ts
  src/mocks/MyPageChecks.ts
  src/mocks/MyPageMocks.ts
  src/mocks/PopUpDetailItemMocks.ts
  src/mocks/PopUpDetailMocks.ts
  src/mocks/PopUpEntryMocks.ts
  src/mocks/ReservationMocks.ts
  src/mocks/SearchScreenMocks.ts
  src/mocks/SurveyQuestionsMocks.ts
  src/types/PopUpEntryScreen.ts
Labels: 🐛 bug/error, ♻️ refactor
